//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridSimple.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int xID { get; set; }
        public string xFirstName { get; set; }
        public string xLastName { get; set; }
        public string xFatherName { get; set; }
        public string xNationalID { get; set; }
        public string xBirthCartPlace { get; set; }
    }
}
